package store

// migrations are applied in order, once each, recorded in schema_migrations.
// Never edit an applied migration — append a new one.
var migrations = []struct {
	Name string
	SQL  string
}{
	{"001_core", `
CREATE TABLE users (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  email         TEXT NOT NULL UNIQUE,
  name          TEXT NOT NULL DEFAULT '',
  password_hash TEXT NOT NULL,
  role          TEXT NOT NULL DEFAULT 'member',
  -- The user's own LLM credentials. Empty rather than NULL: the embedded
  -- engine rejects NULL on columns it considers constrained, and an empty
  -- string is the natural "not configured" value here anyway.
  ai_api_key    TEXT NOT NULL DEFAULT '',
  ai_base_url   TEXT NOT NULL DEFAULT '',
  ai_model      TEXT NOT NULL DEFAULT '',
  created_at    TEXT NOT NULL,
  last_login_at TEXT NOT NULL DEFAULT ''
);

CREATE TABLE sessions (
  token      TEXT PRIMARY KEY,
  user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  user_agent TEXT NOT NULL DEFAULT ''
);
CREATE INDEX idx_sessions_user ON sessions(user_id);

-- A company is whoever performed a test or supplied a service: the pool store,
-- a service contractor, or the owner testing at home.
CREATE TABLE companies (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  kind       TEXT NOT NULL DEFAULT 'store',
  phone      TEXT NOT NULL DEFAULT '',
  email      TEXT NOT NULL DEFAULT '',
  address    TEXT NOT NULL DEFAULT '',
  notes      TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL,
  UNIQUE(user_id, name)
);

CREATE TABLE pools (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id           INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name              TEXT NOT NULL,
  customer_name     TEXT NOT NULL DEFAULT '',
  site_address      TEXT NOT NULL DEFAULT '',
  volume_l          REAL NOT NULL,
  water_type        TEXT NOT NULL DEFAULT 'Swimming Pool',
  treatment_profile TEXT NOT NULL DEFAULT '',
  grade             TEXT NOT NULL DEFAULT '',
  surface           TEXT NOT NULL DEFAULT 'vinyl',
  sanitizer         TEXT NOT NULL DEFAULT 'chlorine',
  location          TEXT NOT NULL DEFAULT 'Outdoor',
  salt_pool         INTEGER NOT NULL DEFAULT 0,
  created_at        TEXT NOT NULL,
  UNIQUE(user_id, name)
);

-- One water analysis. Every reading is nullable: a strip test fills three
-- fields, a shop photometer fills twenty.
CREATE TABLE tests (
  id                       INTEGER PRIMARY KEY AUTOINCREMENT,
  pool_id                  INTEGER NOT NULL REFERENCES pools(id) ON DELETE CASCADE,
  company_id               INTEGER REFERENCES companies(id) ON DELETE SET NULL,
  tested_at                TEXT NOT NULL,
  operator                 TEXT NOT NULL DEFAULT '',
  test_count               INTEGER,
  source                   TEXT NOT NULL DEFAULT 'manual',

  free_chlorine            REAL,
  total_chlorine           REAL,
  combined_chlorine        REAL,
  total_salt               REAL,
  bromine                  REAL,

  ph                       REAL,
  total_alkalinity         REAL,
  total_alkalinity_adjusted REAL,
  calcium_hardness         REAL,

  cyanuric_acid            REAL,
  phosphate                REAL,
  borate                   REAL,
  tds                      REAL,
  temperature              REAL,

  total_copper             REAL,
  free_copper              REAL,
  combined_copper          REAL,
  iron                     REAL,

  wqi                      REAL,   -- as printed by the testing lab, if given
  lsi                      REAL,   -- computed by us
  score                    INTEGER,-- 0-100 derived water quality score
  weather                  TEXT NOT NULL DEFAULT '',
  created_at               TEXT NOT NULL
);
CREATE INDEX idx_tests_pool_date ON tests(pool_id, tested_at DESC);

-- Notes attached to a test, authored by a human or generated by the AI.
CREATE TABLE notes (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  test_id    INTEGER REFERENCES tests(id) ON DELETE CASCADE,
  pool_id    INTEGER NOT NULL REFERENCES pools(id) ON DELETE CASCADE,
  user_id    INTEGER REFERENCES users(id) ON DELETE SET NULL,
  kind       TEXT NOT NULL DEFAULT 'human',  -- human | ai
  body       TEXT NOT NULL,
  model      TEXT NOT NULL DEFAULT '',
  meta       TEXT NOT NULL DEFAULT '',       -- JSON payload for AI responses
  created_at TEXT NOT NULL
);
CREATE INDEX idx_notes_test ON notes(test_id);
CREATE INDEX idx_notes_pool ON notes(pool_id, created_at DESC);

-- Treatments recommended for a test, and whether they were actually applied.
CREATE TABLE treatments (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  test_id    INTEGER NOT NULL REFERENCES tests(id) ON DELETE CASCADE,
  parameter  TEXT NOT NULL DEFAULT '',
  product    TEXT NOT NULL,
  amount     REAL,
  unit       TEXT NOT NULL DEFAULT '',
  reason     TEXT NOT NULL DEFAULT '',
  note       TEXT NOT NULL DEFAULT '',
  priority   INTEGER NOT NULL DEFAULT 5,
  source     TEXT NOT NULL DEFAULT 'computed', -- computed | report | human
  applied    INTEGER NOT NULL DEFAULT 0,
  applied_at TEXT,
  created_at TEXT NOT NULL
);
CREATE INDEX idx_treatments_test ON treatments(test_id);

CREATE TABLE schema_migrations (
  name       TEXT PRIMARY KEY,
  applied_at TEXT NOT NULL
);
`},

	{"002_seasons_and_logbook", `
-- A season is the operating window between opening and closing the pool.
-- Costs and additions roll up to it.
CREATE TABLE seasons (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  pool_id    INTEGER NOT NULL REFERENCES pools(id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  opened_on  TEXT NOT NULL,
  closed_on  TEXT,
  notes      TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL
);
CREATE INDEX idx_seasons_pool ON seasons(pool_id, opened_on DESC);

-- The logbook: everything that goes into, onto, or is done to the pool.
-- Chemicals, parts, service calls, utilities, anything with a date and
-- optionally a cost. Backdating is the normal case, not an exception.
CREATE TABLE log_entries (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  pool_id     INTEGER NOT NULL REFERENCES pools(id) ON DELETE CASCADE,
  season_id   INTEGER REFERENCES seasons(id) ON DELETE SET NULL,
  company_id  INTEGER REFERENCES companies(id) ON DELETE SET NULL,
  test_id     INTEGER REFERENCES tests(id) ON DELETE SET NULL,
  user_id     INTEGER REFERENCES users(id) ON DELETE SET NULL,

  occurred_on TEXT NOT NULL,   -- date the thing actually happened (YYYY-MM-DD)
  category    TEXT NOT NULL,   -- chemical|equipment|service|maintenance|utility|opening|closing|other
  item        TEXT NOT NULL,   -- "Chlorine", "Salt", "Cartridge filter", "Salt cell", "Service call"
  quantity    REAL,
  unit        TEXT NOT NULL DEFAULT '', -- L|kg|g|ml|bag|jug|puck|hour|each

  -- Cost is stored in minor units (cents) to keep money arithmetic exact.
  cost_cents  INTEGER NOT NULL DEFAULT 0,
  currency    TEXT NOT NULL DEFAULT 'CAD',
  vendor      TEXT NOT NULL DEFAULT '',
  notes       TEXT NOT NULL DEFAULT '',
  created_at  TEXT NOT NULL,
  updated_at  TEXT NOT NULL
);
CREATE INDEX idx_log_pool_date ON log_entries(pool_id, occurred_on DESC);
CREATE INDEX idx_log_season ON log_entries(season_id);
CREATE INDEX idx_log_category ON log_entries(pool_id, category);

-- Receipts and documents. The file itself lives on disk; this row is the
-- metadata plus the link to whatever it pays for.
CREATE TABLE receipts (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  pool_id      INTEGER NOT NULL REFERENCES pools(id) ON DELETE CASCADE,
  user_id      INTEGER REFERENCES users(id) ON DELETE SET NULL,
  filename     TEXT NOT NULL,
  stored_name  TEXT NOT NULL UNIQUE,
  content_type TEXT NOT NULL DEFAULT '',
  size_bytes   INTEGER NOT NULL DEFAULT 0,
  total_cents  INTEGER NOT NULL DEFAULT 0,
  currency     TEXT NOT NULL DEFAULT 'CAD',
  vendor       TEXT NOT NULL DEFAULT '',
  purchased_on TEXT,
  notes        TEXT NOT NULL DEFAULT '',
  created_at   TEXT NOT NULL
);
CREATE INDEX idx_receipts_pool ON receipts(pool_id, created_at DESC);

-- A receipt can cover several line items, and a line item can be split across
-- receipts, so the link is many-to-many.
CREATE TABLE receipt_links (
  receipt_id   INTEGER NOT NULL REFERENCES receipts(id) ON DELETE CASCADE,
  log_entry_id INTEGER NOT NULL REFERENCES log_entries(id) ON DELETE CASCADE,
  PRIMARY KEY (receipt_id, log_entry_id)
);
`},

	{"003_api_keys_and_invites", `
-- Named API keys, several per user, individually revocable. Only the hash is
-- stored; the plaintext key is shown once at creation.
CREATE TABLE api_keys (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name         TEXT NOT NULL,
  prefix       TEXT NOT NULL,          -- first chars, shown in the UI for identification
  key_hash     TEXT NOT NULL UNIQUE,
  scopes       TEXT NOT NULL DEFAULT 'read,write',
  created_at   TEXT NOT NULL,
  last_used_at TEXT,
  expires_at   TEXT,
  revoked_at   TEXT
);
CREATE INDEX idx_api_keys_user ON api_keys(user_id);

-- Single-use invite codes, for when registration is invite-only.
CREATE TABLE invites (
  code       TEXT PRIMARY KEY,
  created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  email      TEXT NOT NULL DEFAULT '',
  note       TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL,
  expires_at TEXT,
  used_at    TEXT,
  used_by    INTEGER REFERENCES users(id) ON DELETE SET NULL
);
`},

	{"004_oauth_identities", `
-- A user can sign in with a password, GitHub, Google, or any combination.
-- Identities are matched to an existing account by verified email.
CREATE TABLE oauth_identities (
  provider     TEXT NOT NULL,          -- github | google
  provider_uid TEXT NOT NULL,
  user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  email        TEXT NOT NULL DEFAULT '',
  avatar_url   TEXT NOT NULL DEFAULT '',
  created_at   TEXT NOT NULL,
  PRIMARY KEY (provider, provider_uid)
);
CREATE INDEX idx_oauth_user ON oauth_identities(user_id);
`},

	{"005_attachments", `
-- Receipts double as the generic attachment store, so a scanned water-analysis
-- sheet is filed the same way a receipt is. Images are downscaled and
-- re-encoded on upload; kind tells the UI how to present them.
ALTER TABLE receipts ADD COLUMN kind TEXT NOT NULL DEFAULT 'receipt';
ALTER TABLE receipts ADD COLUMN test_id INTEGER REFERENCES tests(id) ON DELETE SET NULL;
ALTER TABLE receipts ADD COLUMN width INTEGER NOT NULL DEFAULT 0;
ALTER TABLE receipts ADD COLUMN height INTEGER NOT NULL DEFAULT 0;
ALTER TABLE receipts ADD COLUMN original_bytes INTEGER NOT NULL DEFAULT 0;
CREATE INDEX idx_receipts_test ON receipts(test_id);
`},

	{"006_ai_providers", `
-- A user's own model providers, as an ordered fallback chain rather than a
-- single endpoint: slot 1 is tried first, then 2, then 3. Keys are personal —
-- the operator's key is a convenience for whoever runs the server, not an
-- allowance for everyone who signs up — so an account that configures its own
-- providers uses only those.
--
-- kind separates the two chains. A provider's cheapest text model and its
-- vision model are rarely the same one, and sending a photograph to a
-- text-only model fails at the provider rather than degrading.
CREATE TABLE ai_providers (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind       TEXT NOT NULL DEFAULT 'text',   -- text | vision
  slot       INTEGER NOT NULL,               -- 1 is the primary, then each backup
  provider   TEXT NOT NULL,                  -- deepseek | nvidia | anthropic | openai | ...
  model      TEXT NOT NULL DEFAULT '',
  base_url   TEXT NOT NULL DEFAULT '',       -- only for an endpoint go-ai does not know
  api_key    TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE(user_id, kind, slot)
);
CREATE INDEX idx_ai_providers_user ON ai_providers(user_id, kind, slot);
`},

	{"007_password_resets", `
-- Single-use password reset tokens.
--
-- Only the hash is stored, for the same reason as an API key: a leaked
-- database yields hashes, and a hash cannot be mailed to anybody. The token
-- itself exists only in the link that was sent.
CREATE TABLE password_resets (
  token_hash  TEXT PRIMARY KEY,
  user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at  TEXT NOT NULL,
  expires_at  TEXT NOT NULL,
  used_at     TEXT NOT NULL DEFAULT '',
  requested_ip TEXT NOT NULL DEFAULT ''
);
CREATE INDEX idx_password_resets_user ON password_resets(user_id, created_at DESC);
`},
}
